# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Número 1')),
                ('number_2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Numero 2')),
                ('number_3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Número 3')),
                ('number_4', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Número 4')),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
            },
        ),
    ]
